version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  schedule:
    - cron: '* 0 6 ? * 6 *'
variables:
  global:
    - TOKEN
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - git checkout -B master
          - python3 ./main.py > release.txt
          - git config --global user.email "923463801@qq.com"
          - git config --global user.name "xliuqq"
          - git add README.md CHANGELOG_PROJECTS.md
          - git commit -F release.txt
          - if [ "$?" == "0" ] ; then git push https://923463801%40qq.com:${TOKEN}@gitee.com/cs-open-project/projectsfound.git master ; fi
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
